# ES Module 2
Welcome to Module 2!

Last time, we had our first look at Python and Jupyter notebooks. We learned the basics so we can start moving forward and analyze data. Python is an incredibly powerful tool, and in todays module we'll see just a simple demonstration of the sheer power of it!

## 1. Strings and integers

We will now concrete the ideas of strings versus integers. 

Remeber: you can always go back to past Modules if you forgot anything, as well as ask friends or staff :)

## 1.1 The difference between Strings and integers
For starters, lets refresh on difference between 'strings', which can contain just about everything and are good for storing words or sentences, and integers (natural numbers, with no decimals).
Strings and integers are different *types* of values, even when a string contains the digits of a number. For example, evaluating the following cell causes an error because an integer cannot be added to a string.

In [1]:
8 + "8"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

However, there are built-in functions to convert numbers to strings and strings to numbers. 

    int:   Converts a string of digits to an integer ("int") value
    str:   Converts any value to a string

Try to predict what the following cell will evaluate to, then evaluate it.

In [2]:
8 + int("8")

16

Suppose you're writing a program that looks for dates in a text, and you want your program to find the amount of time that elapsed between two years it has identified.  It doesn't make sense to subtract two texts, but you can first convert the text containing the years into numbers.

**Question 1.1.1.** Finish the code below to compute the number of years that elapsed between `one_year` and `another_year`.  Don't just write the numbers `1618` and `1648` (or `30`); use a conversion function to turn the given text data into numbers.

In [3]:
# Some text data:
one_year = "1618"
another_year = "1648"

# Complete the next line.  Note that we can't just write:
#   another_year - one_year
# If you don't see why, try seeing what happens when you
# write that here.
difference = ...
difference

Ellipsis

## 1.2. Strings as function arguments

String values, like integers, are relatively easy to use.  Using a function called `len` will tell you how long a string is.
Note that it doesn't count *words*, but characters (space is a charater): `len("one small step for man")` is 22, not 5.

**Question 1.2.1.**  Use `len` to find out the number of characters in the very long string in the next cell.  (It's the first sentence of the English translation of the French [Declaration of the Rights of Man](http://avalon.law.yale.edu/18th_century/rightsof.asp).)  The length of a string is the total number of characters in it, including things like spaces and punctuation.  Assign `sentence_length` to that number.

In [4]:
a_very_long_sentence = "The representatives of the French people, organized as a National Assembly, believing that the ignorance, neglect, or contempt of the rights of man are the sole cause of public calamities and of the corruption of governments, have determined to set forth in a solemn declaration the natural, unalienable, and sacred rights of man, in order that this declaration, being constantly before all the members of the Social body, shall remind them continually of their rights and duties; in order that the acts of the legislative power, as well as those of the executive power, may be compared at any moment with the objects and purposes of all political institutions and may thus be more respected, and, lastly, in order that the grievances of the citizens, based hereafter upon simple and incontestable principles, shall tend to the maintenance of the constitution and redound to the happiness of all."
sentence_length = len(a_very_long_sentence)
sentence_length

896

# 2. Arrays

Up to now, we haven't done much that you couldn't do yourself by hand, without going through the trouble of learning Python.  Computers are most useful when you can use a small amount of code to *do the same action* to *many different things*.

For example, in the time it takes you to calculate the 18% tip on a restaurant bill, a laptop can calculate 18% tips for every restaurant bill paid by every human on Earth that day.  (That's if you're pretty fast at doing arithmetic in your head!)

**Arrays** are how we put many values in one place so that we can operate on them as a group. For example, if `billions_of_numbers` is an array of numbers, the expression

    .18 * billions_of_numbers

gives a new array of numbers that's the result of multiplying each number in `billions_of_numbers` by .18 (18%).  Arrays are not limited to numbers; we can also put all the words in a book into an array of strings.

Concretely, an array is a **collection of values of the same type**, like a column in an Excel spreadsheet. 

## 2.1. Making arrays
You can type in the data that goes in an array yourself, but that's not typically how programs work. Normally, we create arrays by loading them from an external source, like a data file.

First, though, let's learn how to do it the hard way.
Don't concern yourself with the next line too much, it is just telling the computer you are using a specific set of tools that we will explore through out the semester. These tools are a part of a 'library' (the set of tools) called 'datascience' and was made right here at Cal!

In [23]:
from datascience import *

Now, to create an array, call the function `make_array`.  Each argument you pass to `make_array` will be in the array it returns.  Run this cell to see an example:

In [24]:
make_array(0.125, 4.75, -1.3)

array([ 0.125,  4.75 , -1.3  ])

Each value in an array (in the above case, the numbers 0.125, 4.75, and -1.3) is called an *element* of that array.

Arrays themselves are also values, just like numbers and strings.  That means you can assign them names or use them as arguments to functions.

**Question 4.1.1.** Make an array containing the numbers 1, 2, and 3, in that order.  Name it `small_numbers`.

In [25]:
small_numbers = make_array(1,2,3)
small_numbers

array([1, 2, 3])

**Question 4.1.2.** Make an array containing the five strings `"Hello"`, `","`, `" "`, `"world"`, and `"!"`.  (The third one is a single space inside quotes.)  Name it `hello_world_components`.

In [26]:
hello_world_components = make_array("Hello", ",", " ", "world", "!")
hello_world_components

array(['Hello', ',', ' ', 'world', '!'], 
      dtype='<U5')

## 2.2. Working with single elements of arrays ("indexing")
Let's work with a more interesting dataset.  The next cell creates an array called `totalInmates` that includes the (estimated) total number of inmates in local jails for the years 2005–2015.

Rather than type in the data manually, we've loaded them from a file on your computer called `inmates_by_year.csv`. 

In [27]:
# Don't worry too much about what goes on in this cell.
import math
import numpy as np
totalInmates = Table.read_table("inmates_by_year.csv").column("Total")
totalInmates

array(['747,500', '765,800', '780,200', '785,500', '767,400', '748,700',
       '735,600', '744,500', '731,200', '744,600', '728,200'], 
      dtype='<U7')

Here's how we get the first element of `totalInmates`, which is the US innmate number in the first year in the dataset, 2005.

In [28]:
totalInmates.item(0)

'747,500'

The value of that expression is the number 747,500 (almost 0.75 milion), because that's the first thing in the array `totalInmates`.

Notice that we wrote `.item(0)`, not `.item(1)`, to get the first element.  This is a weird convention in computer science.  0 is called the *index* of the first item.  It's the number of elements that appear *before* that item.  So 3 is the index of the 4th item.

Here are some more examples.  In the examples, we've given names to the things we get out of `totalInmates`.  Read and run each cell.

In [29]:
# The third element in the array is the total number of inmates in local jails 
# in 2007.
inmates_2007 = totalInmates.item(2)
inmates_2007

'780,200'

In [30]:
# The twelfth element in the array is the total number of inmaes in local jails
# in 2016 (which is 2005 + 11). Unfortunately, we do not have that information in the table. 
# Hence this will spit nonsense. This is why len() is so useful!
inmates_2016 = totalInmates.item(11)
inmates_2016

IndexError: index 11 is out of bounds for axis 0 with size 11

In [31]:
# Since make_array returns an array, we can call .item(3)
# on its output to get its 4th element, just like we
# "chained" together calls to the method "replace" earlier.
make_array(-1, -3, 4, -2).item(3)

-2

**Question 2.2.1.** Set `inmates_2006` to the inmates population in 2006, by getting the appropriate element from `totalInmates` using `item`.

In [32]:
inmates_2006 = totalInmates.item(1)
inmates_2006

'765,800'

## 2.3. Doing something to every element of an array
Arrays are primarily useful for doing the same operation many times, so we don't often have to use `.item` and work with single elements.

##### Logarithms
Here is one simple question we might ask about world population:

> How big was the innmate population in *orders of magnitude* in each year?

The logarithm function is one way of measuring how big a number is. The logarithm (base 10) of a number increases by 1 every time we multiply the number by 10. It's like a measure of how many decimal digits the number has, or how big it is in orders of magnitude.

We could try to answer our question like this, using the `log10` function from the `math` liberary and the `item` method you just saw:

In [33]:
population_2005_magnitude = math.log10(float(totalInmates.item(0)))
population_2006_magnitude = math.log10(float(totalInmates.item(1)))
population_2007_magnitude = math.log10(float(totalInmates.item(2)))

# DOES NOT WORK

ValueError: could not convert string to float: '747,500'

But this is tedious and doesn't really take advantage of the fact that we are using a computer.

Instead, NumPy provides its own version of `log10` that takes the logarithm of each element of an array called `np.log10()`.  It takes a single array of numbers as its argument.  It returns an array of the same length, where the first element of the result is the logarithm of the first element of the argument, and so on.

**Question 2.3.1.** Use it to compute the logarithms of the inmate population in every year.  Give the result (an array of 11 numbers) the name `population_magnitudes`.  Your code should be very short.

In [34]:
population_magnitudes = np.log10(totalInmates)
population_magnitudes

# DOES NOT WORK

TypeError: ufunc 'log10' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

##### Arithmetic
Arithmetic also works `elementwise` on arrays.  

You can do  addition, subtraction, multiplication, and exponentiation on a complete array! For example, you can calculate a tip on several restaurant bills at once (in this case just 3):

In [35]:
restaurant_bills = make_array(20.12, 39.90, 31.01)
print("Restaurant bills:\t", restaurant_bills)
tips = .2 * restaurant_bills
print("Tips:\t\t\t", tips)

Restaurant bills:	 [ 20.12  39.9   31.01]
Tips:			 [ 4.024  7.98   6.202]


**Question 2.3.2.** Suppose the total charge at a restaurant is the original bill plus the tip.  That means we can multiply the original bill by 1.2 to get the total charge.  Compute the total charge for each bill in `restaurant_bills`.

In [36]:
total_charges = 1.2*restaurant_bills
total_charges

array([ 24.144,  47.88 ,  37.212])

The function `sum()` takes a single array of numbers as its argument.  It returns the sum of all the numbers in that array (so it returns a single number, not an array).

**Question 2.3.3.** What was the sum of all the bills in `restaurant_bills`, *including tips*?

In [37]:
sum_of_bills = sum(restaurant_bills)
sum_of_bills

91.030000000000001

## Tables

Arrays are useful when you're considering a single aspect, but it's hard to visualize how different arrays relate to each other. For this, we'll be using tables. Tables can show us different aspects of each element we're looking at.

Click the `run` button on the cell below to see what a table looks like. Don't worry about the commands we've typed quite yet- we'll go over them later in this notebook.

In [38]:
from datascience import *

inmates_by_year = Table.read_table('inmates_by_year.csv')
inmates_by_year

Year | Total   | Standard error/a
2005 | 747,500 |  ~
2006 | 765,800 | 3,550
2007 | 780,200 | 3,720
2008 | 785,500 | 4,020
2009 | 767,400 | 4,230
2010 | 748,700 | 5,430
2011 | 735,600 | 6,010
2012 | 744,500 | 7,680
2013 | 731,200 | 8,040
2014 | 744,600 | 8,380
... (1 rows omitted)

Notice how it says `(1 row omitted)`. Our table is too big to display completely on our screen. We're only shown 10 rows, but there are 11 rows total. We can still access these rows if we'd like. 

Tables are essentially collections of arrays. For example, let's focus on the first column: `year`. We can use the `column` command to select one column from a table. Run the cell below to see how we can extract the array for the first column.

In [39]:
inmates_by_year.column('Year')

array([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015])

When we run this, we get the array corresponding to the first column. Notice that we first include the name of our data table, and then run the `column` function on it. The argument for `column` is the name of the column we're interested in.

**Exercise**: In the cell below, extract the columns corresponding to `Total` and `Standard Error` and save each one as a variable.

In [40]:
total = inmates_by_year.column("Total")
StdE = inmates_by_year.column("Standard error/a")

### Loading Tables from CSV Files

Most of the data we will be working with in this module (and in real life) comes in the form of [CSV (Comma Separated Values) Files](https://en.wikipedia.org/wiki/Comma-separated_values). To load a table from a CSV file, run the command `Table.read_table(name)`, where you replace name with the name of your CSV file. 

**Exercise**: In the cell below, load the table `correctional_population.csv` and assign it to the variable `correctional_population`. Be sure to include the name of the table as a string. 

In [41]:
correctional_population = Table.read_table('correctional_population.csv')
correctional_population

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2000 | 3,060                                                | 1 in 33
2005 | 3,160                                                | 1 in 32
2006 | 3,190                                                | 1 in 31
2007 | 3,210                                                | 1 in 31
2008 | 3,160                                                | 1 in 32
2009 | 3,100                                                | 1 in 32
2010 | 3,000                                                | 1 in 33
2011 | 2,930                                                | 1 in 34
2012 | 2,880                                                | 1 in 35
2013 | 2,830                                                | 1 in 35
... (2 rows omitted)

**Exercise**: Now, extract each column from the table and save each as a different variable.

In [42]:
year = correctional_population.column("Year")
total = correctional_population.column("Number supervised per 100,000 U.S. adult residents/c")
supervised = correctional_population.column("U.S. adult residents under correctional supervision ")

### Making Tables

Though we'll do this less often, you can also make tables of your own. Run the code below for an example:

In [43]:
animals = make_array('dog', 'cat', 'bird', 'spider')
num_legs = make_array(4, 4, 2, 8)
num_legs_table = Table().with_columns(
                    'Animal', animals,
                    'Number of Legs', num_legs)
num_legs_table

Animal | Number of Legs
dog    | 4
cat    | 4
bird   | 2
spider | 8

Let's go over what this code did, step by step. 
1. First, we created an array called `animals` and an array called `num_legs`. Both of these arrays contain the values we wanted to add to our table. 
2. Now, we ran the `Table()` command and assigned the result to `num_legs_table`. In the `Table()` command:
    * The `Table()` part of the command creates an empty table.
    * The `with_columns` part specifies what columns we want. For our arguments, we first include the name of what we want our column to be as a string, then include the name of the array we want to correspond to that name. 
3. Evaluate `num_legs_table`, showing us the result of our commmand.

**Exercise**: In the cell below, create a table with one column of schools, and another column of the states they're in. 

In [46]:
schools = make_array('UC Berkeley', 'Harvard', 'StanfUrd')
states = make_array('CA', 'MA', 'CA')
school_states = Table().with_columns(
                    'Schools', schools,
                    'States', states)
school_states

Schools     | States
UC Berkeley | CA
Harvard     | MA
StanfUrd    | CA

## Sorting Tables

Let's go back to our `inmates_by_year` table. Right now, it's sorted by increasing year. Say we want to, instead, sort our table by the total number of inmates. We can do so using the `sort` command. Examine the code below for an example of how to do so. 

In [47]:
inmates_by_year.sort('Total')

Year | Total   | Standard error/a
2015 | 728,200 | 7,380
2013 | 731,200 | 8,040
2011 | 735,600 | 6,010
2012 | 744,500 | 7,680
2014 | 744,600 | 8,380
2005 | 747,500 |  ~
2010 | 748,700 | 5,430
2006 | 765,800 | 3,550
2009 | 767,400 | 4,230
2007 | 780,200 | 3,720
... (1 rows omitted)

In the command above, `sort` had one argument: the column we'd like to sort by. By default, this will sort ascendingly (the lowest value is at the top). Now, say we want to go in descending order. We can specify an argument called `descending` in our `sort` command. When this argument is `True`, we'll sort in descending order. By default, `descending` is `False`.

Let's sort `inmates_by_year` by descending total now.

In [48]:
inmates_by_year.sort('Total', descending = True)

Year | Total   | Standard error/a
2008 | 785,500 | 4,020
2007 | 780,200 | 3,720
2009 | 767,400 | 4,230
2006 | 765,800 | 3,550
2010 | 748,700 | 5,430
2005 | 747,500 |  ~
2014 | 744,600 | 8,380
2012 | 744,500 | 7,680
2011 | 735,600 | 6,010
2013 | 731,200 | 8,040
... (1 rows omitted)

Note that when we run operations on tables, we aren't modifying the original table, but rather, creating a new table. If we look at `inmates_by_year` for example, it'll still be sorted by ascending year.

If we want to save our modifications, we need to assign them to variables.

In [49]:
inmates_by_year

Year | Total   | Standard error/a
2005 | 747,500 |  ~
2006 | 765,800 | 3,550
2007 | 780,200 | 3,720
2008 | 785,500 | 4,020
2009 | 767,400 | 4,230
2010 | 748,700 | 5,430
2011 | 735,600 | 6,010
2012 | 744,500 | 7,680
2013 | 731,200 | 8,040
2014 | 744,600 | 8,380
... (1 rows omitted)

**Exercise**: Sort `correctional_population` by descending year, and assign it to the variable `desc_correctional_population`. 

In [51]:
sorted_cor_pop = correctional_population.sort('Year', descending = True)
sorted_cor_pop

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2015 | 2,710                                                | 1 in 37
2014 | 2,780                                                | 1 in 36
2013 | 2,830                                                | 1 in 35
2012 | 2,880                                                | 1 in 35
2011 | 2,930                                                | 1 in 34
2010 | 3,000                                                | 1 in 33
2009 | 3,100                                                | 1 in 32
2008 | 3,160                                                | 1 in 32
2007 | 3,210                                                | 1 in 31
2006 | 3,190                                                | 1 in 31
... (2 rows omitted)

**Exercise**: Now, sort `correctional_population` by the column `"Number supervised per 100,000 U.S. adult residents/c"`. Assign this table to the variable `num_supervised_correctional_population`. 

In [53]:
num_supervised_correctional_population = correctional_population.sort("Number supervised per 100,000 U.S. adult residents/c")
num_supervised_correctional_population

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2015 | 2,710                                                | 1 in 37
2014 | 2,780                                                | 1 in 36
2013 | 2,830                                                | 1 in 35
2012 | 2,880                                                | 1 in 35
2011 | 2,930                                                | 1 in 34
2010 | 3,000                                                | 1 in 33
2000 | 3,060                                                | 1 in 33
2009 | 3,100                                                | 1 in 32
2005 | 3,160                                                | 1 in 32
2008 | 3,160                                                | 1 in 32
... (2 rows omitted)

Now, just to check that `correctional_population` hasn't been modified, view it in the cell. Verify that it's the same as it was before we modified it. 

In [54]:
correctional_population

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2000 | 3,060                                                | 1 in 33
2005 | 3,160                                                | 1 in 32
2006 | 3,190                                                | 1 in 31
2007 | 3,210                                                | 1 in 31
2008 | 3,160                                                | 1 in 32
2009 | 3,100                                                | 1 in 32
2010 | 3,000                                                | 1 in 33
2011 | 2,930                                                | 1 in 34
2012 | 2,880                                                | 1 in 35
2013 | 2,830                                                | 1 in 35
... (2 rows omitted)

## Fun with Tables

Now that we know how to do some basic operations with tables, let's try to get something out of the data. The exercises in this section will be slightly more difficult, so be sure to talk them out with your partner and/or ask for help!

**Exercise**: What is the latest year `inmates_by_year` has recorded? Only use table and array operations to get your answer, and put it in the cell below. 

In [55]:
inmates_by_year.item(-1)

/opt/conda/lib/python3.5/site-packages/datascience/tables.py:192: FutureWarning: Implicit column method lookup is deprecated.
  warnings.warn("Implicit column method lookup is deprecated.", FutureWarning)


Year | Total   | Standard error/a
2015 | 728,200 | 7,380

**Exercise**: What was the total inmate population in this year? Again, only use table and array operations to get your answer.

In [58]:
last = inmates_by_year.item(-1)
last.column("Total")

/opt/conda/lib/python3.5/site-packages/datascience/tables.py:192: FutureWarning: Implicit column method lookup is deprecated.
  warnings.warn("Implicit column method lookup is deprecated.", FutureWarning)


array(['728,200'], 
      dtype='<U7')

**Exercise**: What was the minimum inmate population in `inmates_by_year`? 

In [61]:
(inmates_by_year.sort("Total")).item(0)

/opt/conda/lib/python3.5/site-packages/datascience/tables.py:192: FutureWarning: Implicit column method lookup is deprecated.
  warnings.warn("Implicit column method lookup is deprecated.", FutureWarning)


Year | Total   | Standard error/a
2015 | 728,200 | 7,380

**Exercise**: Which year? 2015

**Exercise**: From `num_legs_table`, what is the average number of legs per animal? 

In [63]:
avg = sum(num_legs) / len(num_legs)
avg

4.5

Congratulations, you're done with Module 2!  Be sure to 
- **Save and Checkpoint** from the `File` menu,
- **Download as IPython Notebook**  also from the `File` menu,
- and let staff know you finished.